# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake/bin/cmake

# The command to remove a file.
RM = /opt/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Studia/BEXUS/IRISC-OBSW

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Studia/BEXUS/IRISC-OBSW

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Studia/BEXUS/IRISC-OBSW/CMakeFiles /mnt/c/Studia/BEXUS/IRISC-OBSW/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Studia/BEXUS/IRISC-OBSW/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named irisc-obsw

# Build rule for target.
irisc-obsw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 irisc-obsw
.PHONY : irisc-obsw

# fast build rule for target.
irisc-obsw/fast:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/build
.PHONY : irisc-obsw/fast

src/camera/camera.o: src/camera/camera.c.o

.PHONY : src/camera/camera.o

# target to build an object file
src/camera/camera.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/camera.c.o
.PHONY : src/camera/camera.c.o

src/camera/camera.i: src/camera/camera.c.i

.PHONY : src/camera/camera.i

# target to preprocess a source file
src/camera/camera.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/camera.c.i
.PHONY : src/camera/camera.c.i

src/camera/camera.s: src/camera/camera.c.s

.PHONY : src/camera/camera.s

# target to generate assembly for a file
src/camera/camera.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/camera.c.s
.PHONY : src/camera/camera.c.s

src/camera/camera_control/camera_control.o: src/camera/camera_control/camera_control.c.o

.PHONY : src/camera/camera_control/camera_control.o

# target to build an object file
src/camera/camera_control/camera_control.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/camera_control/camera_control.c.o
.PHONY : src/camera/camera_control/camera_control.c.o

src/camera/camera_control/camera_control.i: src/camera/camera_control/camera_control.c.i

.PHONY : src/camera/camera_control/camera_control.i

# target to preprocess a source file
src/camera/camera_control/camera_control.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/camera_control/camera_control.c.i
.PHONY : src/camera/camera_control/camera_control.c.i

src/camera/camera_control/camera_control.s: src/camera/camera_control/camera_control.c.s

.PHONY : src/camera/camera_control/camera_control.s

# target to generate assembly for a file
src/camera/camera_control/camera_control.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/camera_control/camera_control.c.s
.PHONY : src/camera/camera_control/camera_control.c.s

src/camera/guiding_camera/guiding_camera.o: src/camera/guiding_camera/guiding_camera.c.o

.PHONY : src/camera/guiding_camera/guiding_camera.o

# target to build an object file
src/camera/guiding_camera/guiding_camera.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/guiding_camera/guiding_camera.c.o
.PHONY : src/camera/guiding_camera/guiding_camera.c.o

src/camera/guiding_camera/guiding_camera.i: src/camera/guiding_camera/guiding_camera.c.i

.PHONY : src/camera/guiding_camera/guiding_camera.i

# target to preprocess a source file
src/camera/guiding_camera/guiding_camera.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/guiding_camera/guiding_camera.c.i
.PHONY : src/camera/guiding_camera/guiding_camera.c.i

src/camera/guiding_camera/guiding_camera.s: src/camera/guiding_camera/guiding_camera.c.s

.PHONY : src/camera/guiding_camera/guiding_camera.s

# target to generate assembly for a file
src/camera/guiding_camera/guiding_camera.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/guiding_camera/guiding_camera.c.s
.PHONY : src/camera/guiding_camera/guiding_camera.c.s

src/camera/nir_camera/nir_camera.o: src/camera/nir_camera/nir_camera.c.o

.PHONY : src/camera/nir_camera/nir_camera.o

# target to build an object file
src/camera/nir_camera/nir_camera.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/nir_camera/nir_camera.c.o
.PHONY : src/camera/nir_camera/nir_camera.c.o

src/camera/nir_camera/nir_camera.i: src/camera/nir_camera/nir_camera.c.i

.PHONY : src/camera/nir_camera/nir_camera.i

# target to preprocess a source file
src/camera/nir_camera/nir_camera.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/nir_camera/nir_camera.c.i
.PHONY : src/camera/nir_camera/nir_camera.c.i

src/camera/nir_camera/nir_camera.s: src/camera/nir_camera/nir_camera.c.s

.PHONY : src/camera/nir_camera/nir_camera.s

# target to generate assembly for a file
src/camera/nir_camera/nir_camera.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/nir_camera/nir_camera.c.s
.PHONY : src/camera/nir_camera/nir_camera.c.s

src/camera/sanity_camera/sanity_camera.o: src/camera/sanity_camera/sanity_camera.c.o

.PHONY : src/camera/sanity_camera/sanity_camera.o

# target to build an object file
src/camera/sanity_camera/sanity_camera.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/sanity_camera/sanity_camera.c.o
.PHONY : src/camera/sanity_camera/sanity_camera.c.o

src/camera/sanity_camera/sanity_camera.i: src/camera/sanity_camera/sanity_camera.c.i

.PHONY : src/camera/sanity_camera/sanity_camera.i

# target to preprocess a source file
src/camera/sanity_camera/sanity_camera.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/sanity_camera/sanity_camera.c.i
.PHONY : src/camera/sanity_camera/sanity_camera.c.i

src/camera/sanity_camera/sanity_camera.s: src/camera/sanity_camera/sanity_camera.c.s

.PHONY : src/camera/sanity_camera/sanity_camera.s

# target to generate assembly for a file
src/camera/sanity_camera/sanity_camera.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/camera/sanity_camera/sanity_camera.c.s
.PHONY : src/camera/sanity_camera/sanity_camera.c.s

src/command/command.o: src/command/command.c.o

.PHONY : src/command/command.o

# target to build an object file
src/command/command.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/command/command.c.o
.PHONY : src/command/command.c.o

src/command/command.i: src/command/command.c.i

.PHONY : src/command/command.i

# target to preprocess a source file
src/command/command.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/command/command.c.i
.PHONY : src/command/command.c.i

src/command/command.s: src/command/command.c.s

.PHONY : src/command/command.s

# target to generate assembly for a file
src/command/command.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/command/command.c.s
.PHONY : src/command/command.c.s

src/data_storage/data_storage.o: src/data_storage/data_storage.c.o

.PHONY : src/data_storage/data_storage.o

# target to build an object file
src/data_storage/data_storage.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/data_storage/data_storage.c.o
.PHONY : src/data_storage/data_storage.c.o

src/data_storage/data_storage.i: src/data_storage/data_storage.c.i

.PHONY : src/data_storage/data_storage.i

# target to preprocess a source file
src/data_storage/data_storage.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/data_storage/data_storage.c.i
.PHONY : src/data_storage/data_storage.c.i

src/data_storage/data_storage.s: src/data_storage/data_storage.c.s

.PHONY : src/data_storage/data_storage.s

# target to generate assembly for a file
src/data_storage/data_storage.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/data_storage/data_storage.c.s
.PHONY : src/data_storage/data_storage.c.s

src/e_link/e_link.o: src/e_link/e_link.c.o

.PHONY : src/e_link/e_link.o

# target to build an object file
src/e_link/e_link.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/e_link/e_link.c.o
.PHONY : src/e_link/e_link.c.o

src/e_link/e_link.i: src/e_link/e_link.c.i

.PHONY : src/e_link/e_link.i

# target to preprocess a source file
src/e_link/e_link.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/e_link/e_link.c.i
.PHONY : src/e_link/e_link.c.i

src/e_link/e_link.s: src/e_link/e_link.c.s

.PHONY : src/e_link/e_link.s

# target to generate assembly for a file
src/e_link/e_link.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/e_link/e_link.c.s
.PHONY : src/e_link/e_link.c.s

src/global_utils/global_utils.o: src/global_utils/global_utils.c.o

.PHONY : src/global_utils/global_utils.o

# target to build an object file
src/global_utils/global_utils.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/global_utils/global_utils.c.o
.PHONY : src/global_utils/global_utils.c.o

src/global_utils/global_utils.i: src/global_utils/global_utils.c.i

.PHONY : src/global_utils/global_utils.i

# target to preprocess a source file
src/global_utils/global_utils.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/global_utils/global_utils.c.i
.PHONY : src/global_utils/global_utils.c.i

src/global_utils/global_utils.s: src/global_utils/global_utils.c.s

.PHONY : src/global_utils/global_utils.s

# target to generate assembly for a file
src/global_utils/global_utils.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/global_utils/global_utils.c.s
.PHONY : src/global_utils/global_utils.c.s

src/i2c/i2c.o: src/i2c/i2c.c.o

.PHONY : src/i2c/i2c.o

# target to build an object file
src/i2c/i2c.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/i2c/i2c.c.o
.PHONY : src/i2c/i2c.c.o

src/i2c/i2c.i: src/i2c/i2c.c.i

.PHONY : src/i2c/i2c.i

# target to preprocess a source file
src/i2c/i2c.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/i2c/i2c.c.i
.PHONY : src/i2c/i2c.c.i

src/i2c/i2c.s: src/i2c/i2c.c.s

.PHONY : src/i2c/i2c.s

# target to generate assembly for a file
src/i2c/i2c.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/i2c/i2c.c.s
.PHONY : src/i2c/i2c.c.s

src/img_processing/data_queue/data_queue.o: src/img_processing/data_queue/data_queue.c.o

.PHONY : src/img_processing/data_queue/data_queue.o

# target to build an object file
src/img_processing/data_queue/data_queue.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/img_processing/data_queue/data_queue.c.o
.PHONY : src/img_processing/data_queue/data_queue.c.o

src/img_processing/data_queue/data_queue.i: src/img_processing/data_queue/data_queue.c.i

.PHONY : src/img_processing/data_queue/data_queue.i

# target to preprocess a source file
src/img_processing/data_queue/data_queue.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/img_processing/data_queue/data_queue.c.i
.PHONY : src/img_processing/data_queue/data_queue.c.i

src/img_processing/data_queue/data_queue.s: src/img_processing/data_queue/data_queue.c.s

.PHONY : src/img_processing/data_queue/data_queue.s

# target to generate assembly for a file
src/img_processing/data_queue/data_queue.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/img_processing/data_queue/data_queue.c.s
.PHONY : src/img_processing/data_queue/data_queue.c.s

src/img_processing/image_handler/image_handler.o: src/img_processing/image_handler/image_handler.c.o

.PHONY : src/img_processing/image_handler/image_handler.o

# target to build an object file
src/img_processing/image_handler/image_handler.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/img_processing/image_handler/image_handler.c.o
.PHONY : src/img_processing/image_handler/image_handler.c.o

src/img_processing/image_handler/image_handler.i: src/img_processing/image_handler/image_handler.c.i

.PHONY : src/img_processing/image_handler/image_handler.i

# target to preprocess a source file
src/img_processing/image_handler/image_handler.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/img_processing/image_handler/image_handler.c.i
.PHONY : src/img_processing/image_handler/image_handler.c.i

src/img_processing/image_handler/image_handler.s: src/img_processing/image_handler/image_handler.c.s

.PHONY : src/img_processing/image_handler/image_handler.s

# target to generate assembly for a file
src/img_processing/image_handler/image_handler.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/img_processing/image_handler/image_handler.c.s
.PHONY : src/img_processing/image_handler/image_handler.c.s

src/img_processing/img_processing.o: src/img_processing/img_processing.c.o

.PHONY : src/img_processing/img_processing.o

# target to build an object file
src/img_processing/img_processing.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/img_processing/img_processing.c.o
.PHONY : src/img_processing/img_processing.c.o

src/img_processing/img_processing.i: src/img_processing/img_processing.c.i

.PHONY : src/img_processing/img_processing.i

# target to preprocess a source file
src/img_processing/img_processing.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/img_processing/img_processing.c.i
.PHONY : src/img_processing/img_processing.c.i

src/img_processing/img_processing.s: src/img_processing/img_processing.c.s

.PHONY : src/img_processing/img_processing.s

# target to generate assembly for a file
src/img_processing/img_processing.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/img_processing/img_processing.c.s
.PHONY : src/img_processing/img_processing.c.s

src/init/init.o: src/init/init.c.o

.PHONY : src/init/init.o

# target to build an object file
src/init/init.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/init/init.c.o
.PHONY : src/init/init.c.o

src/init/init.i: src/init/init.c.i

.PHONY : src/init/init.i

# target to preprocess a source file
src/init/init.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/init/init.c.i
.PHONY : src/init/init.c.i

src/init/init.s: src/init/init.c.s

.PHONY : src/init/init.s

# target to generate assembly for a file
src/init/init.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/init/init.c.s
.PHONY : src/init/init.c.s

src/mode/mode.o: src/mode/mode.c.o

.PHONY : src/mode/mode.o

# target to build an object file
src/mode/mode.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/mode/mode.c.o
.PHONY : src/mode/mode.c.o

src/mode/mode.i: src/mode/mode.c.i

.PHONY : src/mode/mode.i

# target to preprocess a source file
src/mode/mode.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/mode/mode.c.i
.PHONY : src/mode/mode.c.i

src/mode/mode.s: src/mode/mode.c.s

.PHONY : src/mode/mode.s

# target to generate assembly for a file
src/mode/mode.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/mode/mode.c.s
.PHONY : src/mode/mode.c.s

src/sensors/orientation/orientation.o: src/sensors/orientation/orientation.c.o

.PHONY : src/sensors/orientation/orientation.o

# target to build an object file
src/sensors/orientation/orientation.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/orientation/orientation.c.o
.PHONY : src/sensors/orientation/orientation.c.o

src/sensors/orientation/orientation.i: src/sensors/orientation/orientation.c.i

.PHONY : src/sensors/orientation/orientation.i

# target to preprocess a source file
src/sensors/orientation/orientation.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/orientation/orientation.c.i
.PHONY : src/sensors/orientation/orientation.c.i

src/sensors/orientation/orientation.s: src/sensors/orientation/orientation.c.s

.PHONY : src/sensors/orientation/orientation.s

# target to generate assembly for a file
src/sensors/orientation/orientation.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/orientation/orientation.c.s
.PHONY : src/sensors/orientation/orientation.c.s

src/sensors/sensor_poller/sensor_poller.o: src/sensors/sensor_poller/sensor_poller.c.o

.PHONY : src/sensors/sensor_poller/sensor_poller.o

# target to build an object file
src/sensors/sensor_poller/sensor_poller.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/sensor_poller/sensor_poller.c.o
.PHONY : src/sensors/sensor_poller/sensor_poller.c.o

src/sensors/sensor_poller/sensor_poller.i: src/sensors/sensor_poller/sensor_poller.c.i

.PHONY : src/sensors/sensor_poller/sensor_poller.i

# target to preprocess a source file
src/sensors/sensor_poller/sensor_poller.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/sensor_poller/sensor_poller.c.i
.PHONY : src/sensors/sensor_poller/sensor_poller.c.i

src/sensors/sensor_poller/sensor_poller.s: src/sensors/sensor_poller/sensor_poller.c.s

.PHONY : src/sensors/sensor_poller/sensor_poller.s

# target to generate assembly for a file
src/sensors/sensor_poller/sensor_poller.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/sensor_poller/sensor_poller.c.s
.PHONY : src/sensors/sensor_poller/sensor_poller.c.s

src/sensors/sensors.o: src/sensors/sensors.c.o

.PHONY : src/sensors/sensors.o

# target to build an object file
src/sensors/sensors.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/sensors.c.o
.PHONY : src/sensors/sensors.c.o

src/sensors/sensors.i: src/sensors/sensors.c.i

.PHONY : src/sensors/sensors.i

# target to preprocess a source file
src/sensors/sensors.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/sensors.c.i
.PHONY : src/sensors/sensors.c.i

src/sensors/sensors.s: src/sensors/sensors.c.s

.PHONY : src/sensors/sensors.s

# target to generate assembly for a file
src/sensors/sensors.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/sensors.c.s
.PHONY : src/sensors/sensors.c.s

src/sensors/sun/sun.o: src/sensors/sun/sun.c.o

.PHONY : src/sensors/sun/sun.o

# target to build an object file
src/sensors/sun/sun.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/sun/sun.c.o
.PHONY : src/sensors/sun/sun.c.o

src/sensors/sun/sun.i: src/sensors/sun/sun.c.i

.PHONY : src/sensors/sun/sun.i

# target to preprocess a source file
src/sensors/sun/sun.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/sun/sun.c.i
.PHONY : src/sensors/sun/sun.c.i

src/sensors/sun/sun.s: src/sensors/sun/sun.c.s

.PHONY : src/sensors/sun/sun.s

# target to generate assembly for a file
src/sensors/sun/sun.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/sun/sun.c.s
.PHONY : src/sensors/sun/sun.c.s

src/sensors/temperature/temperature.o: src/sensors/temperature/temperature.c.o

.PHONY : src/sensors/temperature/temperature.o

# target to build an object file
src/sensors/temperature/temperature.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/temperature/temperature.c.o
.PHONY : src/sensors/temperature/temperature.c.o

src/sensors/temperature/temperature.i: src/sensors/temperature/temperature.c.i

.PHONY : src/sensors/temperature/temperature.i

# target to preprocess a source file
src/sensors/temperature/temperature.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/temperature/temperature.c.i
.PHONY : src/sensors/temperature/temperature.c.i

src/sensors/temperature/temperature.s: src/sensors/temperature/temperature.c.s

.PHONY : src/sensors/temperature/temperature.s

# target to generate assembly for a file
src/sensors/temperature/temperature.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/sensors/temperature/temperature.c.s
.PHONY : src/sensors/temperature/temperature.c.s

src/spi/spi.o: src/spi/spi.c.o

.PHONY : src/spi/spi.o

# target to build an object file
src/spi/spi.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/spi/spi.c.o
.PHONY : src/spi/spi.c.o

src/spi/spi.i: src/spi/spi.c.i

.PHONY : src/spi/spi.i

# target to preprocess a source file
src/spi/spi.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/spi/spi.c.i
.PHONY : src/spi/spi.c.i

src/spi/spi.s: src/spi/spi.c.s

.PHONY : src/spi/spi.s

# target to generate assembly for a file
src/spi/spi.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/spi/spi.c.s
.PHONY : src/spi/spi.c.s

src/telemetry/downlink/downlink.o: src/telemetry/downlink/downlink.c.o

.PHONY : src/telemetry/downlink/downlink.o

# target to build an object file
src/telemetry/downlink/downlink.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/telemetry/downlink/downlink.c.o
.PHONY : src/telemetry/downlink/downlink.c.o

src/telemetry/downlink/downlink.i: src/telemetry/downlink/downlink.c.i

.PHONY : src/telemetry/downlink/downlink.i

# target to preprocess a source file
src/telemetry/downlink/downlink.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/telemetry/downlink/downlink.c.i
.PHONY : src/telemetry/downlink/downlink.c.i

src/telemetry/downlink/downlink.s: src/telemetry/downlink/downlink.c.s

.PHONY : src/telemetry/downlink/downlink.s

# target to generate assembly for a file
src/telemetry/downlink/downlink.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/telemetry/downlink/downlink.c.s
.PHONY : src/telemetry/downlink/downlink.c.s

src/telemetry/downlink_queue/downlink_queue.o: src/telemetry/downlink_queue/downlink_queue.c.o

.PHONY : src/telemetry/downlink_queue/downlink_queue.o

# target to build an object file
src/telemetry/downlink_queue/downlink_queue.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/telemetry/downlink_queue/downlink_queue.c.o
.PHONY : src/telemetry/downlink_queue/downlink_queue.c.o

src/telemetry/downlink_queue/downlink_queue.i: src/telemetry/downlink_queue/downlink_queue.c.i

.PHONY : src/telemetry/downlink_queue/downlink_queue.i

# target to preprocess a source file
src/telemetry/downlink_queue/downlink_queue.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/telemetry/downlink_queue/downlink_queue.c.i
.PHONY : src/telemetry/downlink_queue/downlink_queue.c.i

src/telemetry/downlink_queue/downlink_queue.s: src/telemetry/downlink_queue/downlink_queue.c.s

.PHONY : src/telemetry/downlink_queue/downlink_queue.s

# target to generate assembly for a file
src/telemetry/downlink_queue/downlink_queue.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/telemetry/downlink_queue/downlink_queue.c.s
.PHONY : src/telemetry/downlink_queue/downlink_queue.c.s

src/telemetry/telemetry.o: src/telemetry/telemetry.c.o

.PHONY : src/telemetry/telemetry.o

# target to build an object file
src/telemetry/telemetry.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/telemetry/telemetry.c.o
.PHONY : src/telemetry/telemetry.c.o

src/telemetry/telemetry.i: src/telemetry/telemetry.c.i

.PHONY : src/telemetry/telemetry.i

# target to preprocess a source file
src/telemetry/telemetry.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/telemetry/telemetry.c.i
.PHONY : src/telemetry/telemetry.c.i

src/telemetry/telemetry.s: src/telemetry/telemetry.c.s

.PHONY : src/telemetry/telemetry.s

# target to generate assembly for a file
src/telemetry/telemetry.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/telemetry/telemetry.c.s
.PHONY : src/telemetry/telemetry.c.s

src/thermal/thermal.o: src/thermal/thermal.c.o

.PHONY : src/thermal/thermal.o

# target to build an object file
src/thermal/thermal.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/thermal/thermal.c.o
.PHONY : src/thermal/thermal.c.o

src/thermal/thermal.i: src/thermal/thermal.c.i

.PHONY : src/thermal/thermal.i

# target to preprocess a source file
src/thermal/thermal.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/thermal/thermal.c.i
.PHONY : src/thermal/thermal.c.i

src/thermal/thermal.s: src/thermal/thermal.c.s

.PHONY : src/thermal/thermal.s

# target to generate assembly for a file
src/thermal/thermal.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/thermal/thermal.c.s
.PHONY : src/thermal/thermal.c.s

src/tracking/controller/controller.o: src/tracking/controller/controller.c.o

.PHONY : src/tracking/controller/controller.o

# target to build an object file
src/tracking/controller/controller.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/controller.c.o
.PHONY : src/tracking/controller/controller.c.o

src/tracking/controller/controller.i: src/tracking/controller/controller.c.i

.PHONY : src/tracking/controller/controller.i

# target to preprocess a source file
src/tracking/controller/controller.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/controller.c.i
.PHONY : src/tracking/controller/controller.c.i

src/tracking/controller/controller.s: src/tracking/controller/controller.c.s

.PHONY : src/tracking/controller/controller.s

# target to generate assembly for a file
src/tracking/controller/controller.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/controller.c.s
.PHONY : src/tracking/controller/controller.c.s

src/tracking/controller/simple_sim_grt_rtw/rtGetInf.o: src/tracking/controller/simple_sim_grt_rtw/rtGetInf.c.o

.PHONY : src/tracking/controller/simple_sim_grt_rtw/rtGetInf.o

# target to build an object file
src/tracking/controller/simple_sim_grt_rtw/rtGetInf.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/simple_sim_grt_rtw/rtGetInf.c.o
.PHONY : src/tracking/controller/simple_sim_grt_rtw/rtGetInf.c.o

src/tracking/controller/simple_sim_grt_rtw/rtGetInf.i: src/tracking/controller/simple_sim_grt_rtw/rtGetInf.c.i

.PHONY : src/tracking/controller/simple_sim_grt_rtw/rtGetInf.i

# target to preprocess a source file
src/tracking/controller/simple_sim_grt_rtw/rtGetInf.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/simple_sim_grt_rtw/rtGetInf.c.i
.PHONY : src/tracking/controller/simple_sim_grt_rtw/rtGetInf.c.i

src/tracking/controller/simple_sim_grt_rtw/rtGetInf.s: src/tracking/controller/simple_sim_grt_rtw/rtGetInf.c.s

.PHONY : src/tracking/controller/simple_sim_grt_rtw/rtGetInf.s

# target to generate assembly for a file
src/tracking/controller/simple_sim_grt_rtw/rtGetInf.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/simple_sim_grt_rtw/rtGetInf.c.s
.PHONY : src/tracking/controller/simple_sim_grt_rtw/rtGetInf.c.s

src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.o: src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.c.o

.PHONY : src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.o

# target to build an object file
src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.c.o
.PHONY : src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.c.o

src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.i: src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.c.i

.PHONY : src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.i

# target to preprocess a source file
src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.c.i
.PHONY : src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.c.i

src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.s: src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.c.s

.PHONY : src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.s

# target to generate assembly for a file
src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.c.s
.PHONY : src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.c.s

src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.o: src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.c.o

.PHONY : src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.o

# target to build an object file
src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.c.o
.PHONY : src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.c.o

src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.i: src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.c.i

.PHONY : src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.i

# target to preprocess a source file
src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.c.i
.PHONY : src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.c.i

src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.s: src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.c.s

.PHONY : src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.s

# target to generate assembly for a file
src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.c.s
.PHONY : src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.c.s

src/tracking/controller/simple_sim_grt_rtw/simple_sim.o: src/tracking/controller/simple_sim_grt_rtw/simple_sim.c.o

.PHONY : src/tracking/controller/simple_sim_grt_rtw/simple_sim.o

# target to build an object file
src/tracking/controller/simple_sim_grt_rtw/simple_sim.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/simple_sim_grt_rtw/simple_sim.c.o
.PHONY : src/tracking/controller/simple_sim_grt_rtw/simple_sim.c.o

src/tracking/controller/simple_sim_grt_rtw/simple_sim.i: src/tracking/controller/simple_sim_grt_rtw/simple_sim.c.i

.PHONY : src/tracking/controller/simple_sim_grt_rtw/simple_sim.i

# target to preprocess a source file
src/tracking/controller/simple_sim_grt_rtw/simple_sim.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/simple_sim_grt_rtw/simple_sim.c.i
.PHONY : src/tracking/controller/simple_sim_grt_rtw/simple_sim.c.i

src/tracking/controller/simple_sim_grt_rtw/simple_sim.s: src/tracking/controller/simple_sim_grt_rtw/simple_sim.c.s

.PHONY : src/tracking/controller/simple_sim_grt_rtw/simple_sim.s

# target to generate assembly for a file
src/tracking/controller/simple_sim_grt_rtw/simple_sim.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/controller/simple_sim_grt_rtw/simple_sim.c.s
.PHONY : src/tracking/controller/simple_sim_grt_rtw/simple_sim.c.s

src/tracking/current_target/current_target.o: src/tracking/current_target/current_target.c.o

.PHONY : src/tracking/current_target/current_target.o

# target to build an object file
src/tracking/current_target/current_target.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/current_target/current_target.c.o
.PHONY : src/tracking/current_target/current_target.c.o

src/tracking/current_target/current_target.i: src/tracking/current_target/current_target.c.i

.PHONY : src/tracking/current_target/current_target.i

# target to preprocess a source file
src/tracking/current_target/current_target.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/current_target/current_target.c.i
.PHONY : src/tracking/current_target/current_target.c.i

src/tracking/current_target/current_target.s: src/tracking/current_target/current_target.c.s

.PHONY : src/tracking/current_target/current_target.s

# target to generate assembly for a file
src/tracking/current_target/current_target.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/current_target/current_target.c.s
.PHONY : src/tracking/current_target/current_target.c.s

src/tracking/gimbal/gimbal.o: src/tracking/gimbal/gimbal.c.o

.PHONY : src/tracking/gimbal/gimbal.o

# target to build an object file
src/tracking/gimbal/gimbal.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/gimbal/gimbal.c.o
.PHONY : src/tracking/gimbal/gimbal.c.o

src/tracking/gimbal/gimbal.i: src/tracking/gimbal/gimbal.c.i

.PHONY : src/tracking/gimbal/gimbal.i

# target to preprocess a source file
src/tracking/gimbal/gimbal.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/gimbal/gimbal.c.i
.PHONY : src/tracking/gimbal/gimbal.c.i

src/tracking/gimbal/gimbal.s: src/tracking/gimbal/gimbal.c.s

.PHONY : src/tracking/gimbal/gimbal.s

# target to generate assembly for a file
src/tracking/gimbal/gimbal.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/gimbal/gimbal.c.s
.PHONY : src/tracking/gimbal/gimbal.c.s

src/tracking/target_selecting/target_selecting.o: src/tracking/target_selecting/target_selecting.c.o

.PHONY : src/tracking/target_selecting/target_selecting.o

# target to build an object file
src/tracking/target_selecting/target_selecting.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/target_selecting/target_selecting.c.o
.PHONY : src/tracking/target_selecting/target_selecting.c.o

src/tracking/target_selecting/target_selecting.i: src/tracking/target_selecting/target_selecting.c.i

.PHONY : src/tracking/target_selecting/target_selecting.i

# target to preprocess a source file
src/tracking/target_selecting/target_selecting.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/target_selecting/target_selecting.c.i
.PHONY : src/tracking/target_selecting/target_selecting.c.i

src/tracking/target_selecting/target_selecting.s: src/tracking/target_selecting/target_selecting.c.s

.PHONY : src/tracking/target_selecting/target_selecting.s

# target to generate assembly for a file
src/tracking/target_selecting/target_selecting.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/target_selecting/target_selecting.c.s
.PHONY : src/tracking/target_selecting/target_selecting.c.s

src/tracking/tracking.o: src/tracking/tracking.c.o

.PHONY : src/tracking/tracking.o

# target to build an object file
src/tracking/tracking.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/tracking.c.o
.PHONY : src/tracking/tracking.c.o

src/tracking/tracking.i: src/tracking/tracking.c.i

.PHONY : src/tracking/tracking.i

# target to preprocess a source file
src/tracking/tracking.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/tracking.c.i
.PHONY : src/tracking/tracking.c.i

src/tracking/tracking.s: src/tracking/tracking.c.s

.PHONY : src/tracking/tracking.s

# target to generate assembly for a file
src/tracking/tracking.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/tracking/tracking.c.s
.PHONY : src/tracking/tracking.c.s

src/watchdog/watchdog.o: src/watchdog/watchdog.c.o

.PHONY : src/watchdog/watchdog.o

# target to build an object file
src/watchdog/watchdog.c.o:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/watchdog/watchdog.c.o
.PHONY : src/watchdog/watchdog.c.o

src/watchdog/watchdog.i: src/watchdog/watchdog.c.i

.PHONY : src/watchdog/watchdog.i

# target to preprocess a source file
src/watchdog/watchdog.c.i:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/watchdog/watchdog.c.i
.PHONY : src/watchdog/watchdog.c.i

src/watchdog/watchdog.s: src/watchdog/watchdog.c.s

.PHONY : src/watchdog/watchdog.s

# target to generate assembly for a file
src/watchdog/watchdog.c.s:
	$(MAKE) -f CMakeFiles/irisc-obsw.dir/build.make CMakeFiles/irisc-obsw.dir/src/watchdog/watchdog.c.s
.PHONY : src/watchdog/watchdog.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... irisc-obsw"
	@echo "... edit_cache"
	@echo "... src/camera/camera.o"
	@echo "... src/camera/camera.i"
	@echo "... src/camera/camera.s"
	@echo "... src/camera/camera_control/camera_control.o"
	@echo "... src/camera/camera_control/camera_control.i"
	@echo "... src/camera/camera_control/camera_control.s"
	@echo "... src/camera/guiding_camera/guiding_camera.o"
	@echo "... src/camera/guiding_camera/guiding_camera.i"
	@echo "... src/camera/guiding_camera/guiding_camera.s"
	@echo "... src/camera/nir_camera/nir_camera.o"
	@echo "... src/camera/nir_camera/nir_camera.i"
	@echo "... src/camera/nir_camera/nir_camera.s"
	@echo "... src/camera/sanity_camera/sanity_camera.o"
	@echo "... src/camera/sanity_camera/sanity_camera.i"
	@echo "... src/camera/sanity_camera/sanity_camera.s"
	@echo "... src/command/command.o"
	@echo "... src/command/command.i"
	@echo "... src/command/command.s"
	@echo "... src/data_storage/data_storage.o"
	@echo "... src/data_storage/data_storage.i"
	@echo "... src/data_storage/data_storage.s"
	@echo "... src/e_link/e_link.o"
	@echo "... src/e_link/e_link.i"
	@echo "... src/e_link/e_link.s"
	@echo "... src/global_utils/global_utils.o"
	@echo "... src/global_utils/global_utils.i"
	@echo "... src/global_utils/global_utils.s"
	@echo "... src/i2c/i2c.o"
	@echo "... src/i2c/i2c.i"
	@echo "... src/i2c/i2c.s"
	@echo "... src/img_processing/data_queue/data_queue.o"
	@echo "... src/img_processing/data_queue/data_queue.i"
	@echo "... src/img_processing/data_queue/data_queue.s"
	@echo "... src/img_processing/image_handler/image_handler.o"
	@echo "... src/img_processing/image_handler/image_handler.i"
	@echo "... src/img_processing/image_handler/image_handler.s"
	@echo "... src/img_processing/img_processing.o"
	@echo "... src/img_processing/img_processing.i"
	@echo "... src/img_processing/img_processing.s"
	@echo "... src/init/init.o"
	@echo "... src/init/init.i"
	@echo "... src/init/init.s"
	@echo "... src/mode/mode.o"
	@echo "... src/mode/mode.i"
	@echo "... src/mode/mode.s"
	@echo "... src/sensors/orientation/orientation.o"
	@echo "... src/sensors/orientation/orientation.i"
	@echo "... src/sensors/orientation/orientation.s"
	@echo "... src/sensors/sensor_poller/sensor_poller.o"
	@echo "... src/sensors/sensor_poller/sensor_poller.i"
	@echo "... src/sensors/sensor_poller/sensor_poller.s"
	@echo "... src/sensors/sensors.o"
	@echo "... src/sensors/sensors.i"
	@echo "... src/sensors/sensors.s"
	@echo "... src/sensors/sun/sun.o"
	@echo "... src/sensors/sun/sun.i"
	@echo "... src/sensors/sun/sun.s"
	@echo "... src/sensors/temperature/temperature.o"
	@echo "... src/sensors/temperature/temperature.i"
	@echo "... src/sensors/temperature/temperature.s"
	@echo "... src/spi/spi.o"
	@echo "... src/spi/spi.i"
	@echo "... src/spi/spi.s"
	@echo "... src/telemetry/downlink/downlink.o"
	@echo "... src/telemetry/downlink/downlink.i"
	@echo "... src/telemetry/downlink/downlink.s"
	@echo "... src/telemetry/downlink_queue/downlink_queue.o"
	@echo "... src/telemetry/downlink_queue/downlink_queue.i"
	@echo "... src/telemetry/downlink_queue/downlink_queue.s"
	@echo "... src/telemetry/telemetry.o"
	@echo "... src/telemetry/telemetry.i"
	@echo "... src/telemetry/telemetry.s"
	@echo "... src/thermal/thermal.o"
	@echo "... src/thermal/thermal.i"
	@echo "... src/thermal/thermal.s"
	@echo "... src/tracking/controller/controller.o"
	@echo "... src/tracking/controller/controller.i"
	@echo "... src/tracking/controller/controller.s"
	@echo "... src/tracking/controller/simple_sim_grt_rtw/rtGetInf.o"
	@echo "... src/tracking/controller/simple_sim_grt_rtw/rtGetInf.i"
	@echo "... src/tracking/controller/simple_sim_grt_rtw/rtGetInf.s"
	@echo "... src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.o"
	@echo "... src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.i"
	@echo "... src/tracking/controller/simple_sim_grt_rtw/rtGetNaN.s"
	@echo "... src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.o"
	@echo "... src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.i"
	@echo "... src/tracking/controller/simple_sim_grt_rtw/rt_nonfinite.s"
	@echo "... src/tracking/controller/simple_sim_grt_rtw/simple_sim.o"
	@echo "... src/tracking/controller/simple_sim_grt_rtw/simple_sim.i"
	@echo "... src/tracking/controller/simple_sim_grt_rtw/simple_sim.s"
	@echo "... src/tracking/current_target/current_target.o"
	@echo "... src/tracking/current_target/current_target.i"
	@echo "... src/tracking/current_target/current_target.s"
	@echo "... src/tracking/gimbal/gimbal.o"
	@echo "... src/tracking/gimbal/gimbal.i"
	@echo "... src/tracking/gimbal/gimbal.s"
	@echo "... src/tracking/target_selecting/target_selecting.o"
	@echo "... src/tracking/target_selecting/target_selecting.i"
	@echo "... src/tracking/target_selecting/target_selecting.s"
	@echo "... src/tracking/tracking.o"
	@echo "... src/tracking/tracking.i"
	@echo "... src/tracking/tracking.s"
	@echo "... src/watchdog/watchdog.o"
	@echo "... src/watchdog/watchdog.i"
	@echo "... src/watchdog/watchdog.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

